# -*- coding: utf-8 -*-
"""Base classes and metaclasses."""

from .bases import (
    MISSING,
    ABSTRACT_TAG,
    FINAL_CLASS_TAG,
    FINAL_METHOD_TAG,
    INITIALIZING_TAG,
    final,
    init_context,
    init,
    simplify_member_names,
    make_base_cls,
    BaseMeta,
    Base,
    abstract_member,
    BaseHashable,
    BaseSized,
    BaseIterable,
    BaseContainer,
    BaseCollection,
    BaseProtectedCollection,
    BaseInteractiveCollection,
    BaseMutableCollection,
)
from .dict import (
    BaseDict,
    BaseProtectedDict,
    BaseInteractiveDict,
    BaseMutableDict,
)
from .list import (
    BaseList,
    BaseProtectedList,
    BaseInteractiveList,
    BaseMutableList,
)
from .set import (
    BaseSet,
    BaseProtectedSet,
    BaseInteractiveSet,
    BaseMutableSet,
)

__all__ = [
    "MISSING",
    "ABSTRACT_TAG",
    "FINAL_CLASS_TAG",
    "FINAL_METHOD_TAG",
    "INITIALIZING_TAG",
    "final",
    "init_context",
    "init",
    "simplify_member_names",
    "make_base_cls",
    "BaseMeta",
    "Base",
    "abstract_member",
    "BaseHashable",
    "BaseSized",
    "BaseIterable",
    "BaseContainer",
    "BaseCollection",
    "BaseProtectedCollection",
    "BaseInteractiveCollection",
    "BaseMutableCollection",
    "BaseDict",
    "BaseProtectedDict",
    "BaseInteractiveDict",
    "BaseMutableDict",
    "BaseList",
    "BaseProtectedList",
    "BaseInteractiveList",
    "BaseMutableList",
    "BaseSet",
    "BaseProtectedSet",
    "BaseInteractiveSet",
    "BaseMutableSet",
]
